version: '3.7'
services:
  tickets_db:
    container_name: tickets_db
    restart: always
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
